version: '3'

services:
  web:
    build: .
    ports:
      - '8000:8000'
    volumes:
      - ./:/usr/src/app
    command: python3 manage.py runserver 0.0.0.0:8000 --settings=diplofy.config.development
    links:
      - 'db'

  db:
    image: 'postgres'
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_PASSWORD=root
    volumes:
      - pgdata:/var/lib/postgresql/data/

volumes:
  pgdata: